dyn_time_dict: null
static_time_dict: null
dyn_directory: null
dyn_file_name: null
dyn: null
stat: null
dyn_tz: null
stat_tz: null
stat_directory: null
stat_file_name: null
feature_lookback: 0
feature_lookahead: 0

futr_feature_size: 0
hist_feature_size: 0
stat_feature_size: 0