model_name: "cnn"
model_class: "transformer"

architecture: 'encoder'
patch_size: 24
conv_kernel_size: [5]
conv_max_pooling: 1
lstm_layers: 0
num_layers: 0
d_model: 128
n_heads: 1
attention: 'full'
max_pooling: 1
dense_units: 1024
num_dense_layers: 2

batch_size: 512
epochs: 100
lr: 0.00013641089979153512
lr_scheduler: no_scheduler
dropout: 0.12068693841666904
early_stopping: True
early_stopping_patience: 10
early_stopping_min_delta: 0
optimizer: 'adamw'

loss_function: 'mse'
quantiles: [0.1, 0.5, 0.9]
