model_name: "lstm"
model_class: "transformer"

architecture: 'encoder'
patch_size: 1
conv_kernel_size: 1
conv_max_pooling: 1
lstm_layers: 2
num_layers: 0
d_model: 128
n_heads: 1
attention: 'full'
max_pooling: 1
dense_units: 128
num_dense_layers: 1

batch_size: 128
epochs: 100
lr: 0.0001
lr_scheduler: no_scheduler
dropout: 0.1
early_stopping: True
early_stopping_patience: 10
early_stopping_min_delta: 0
optimizer: 'adamw'

loss_function: 'mse'
quantiles: [0.1, 0.5, 0.9]
