model_name: "tft"
wandb_project: "tft"

hidden_size: 64
n_head: 4
attn_dropout: 0.0

batch_size: 128
epochs: 100
lr: 0.00010049331200103342
dropout: 0.025532173467814404
early_stopping: True
early_stopping_patience: 10
early_stopping_min_delta: 0
optimizer: 'adamw'
loss_function: 'mse'
quantiles: [0.1, 0.5, 0.9]
