model_name: "transformer"
wandb_project: "transformer"

architecture: 'encoder_decoder'
patch_size: 1
conv_kernel_size: 1
conv_max_pooling: 1
lstm_layers: 0
num_layers: 4
d_model: 64
n_heads: 4
attention: 'full'
max_pooling: 1
dense_units: 128
num_dense_layers: 1

batch_size: 512
epochs: 100
lr: 0.0003331467381538135
lr_scheduler: no_scheduler
dropout: 0.07049059958695196
early_stopping: True
early_stopping_patience: 10
early_stopping_min_delta: 0
optimizer: 'adamw'

loss_function: 'mse'
quantiles: [0.1, 0.5, 0.9]
