model_name: "transformer"
wandb_project: "transformer"

architecture: 'encoder_decoder'
patch_size: 1
conv_kernel_size: 1
conv_max_pooling: 1
lstm_layers: 1
num_layers: 1
d_model: 256
n_heads: 1
attention: 'sparse'
max_pooling: 1
dense_units: 128
num_dense_layers: 2

batch_size: 128
epochs: 100
lr: 0.000376045232593546
lr_scheduler: no_scheduler
dropout: 0.11267230798060256
early_stopping: True
early_stopping_patience: 10
early_stopping_min_delta: 0
optimizer: 'adamw'

loss_function: 'mse'
quantiles: [0.1, 0.5, 0.9]
