dataset_name: transnet_bw
data_directory: _data/transnet_bw/
data_name: TransnetBW_Actual_Total_Load.pkl
data_tz: UTC
start: null
val_split: '2025-11-01'
test_split: '2025-12-01'
end: '2025-12-31 23:59:59'
split_tz: UTC